export const LOADING = "LOADING"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const FETCH_CHARACTER = "FETCH_CHARACTER";
export const FETCH_CHARACTER_ERROR = "FETCH_CHARACTER_ERROR";
export const FETCH_PLANETS = "FETCH_PLANETS";
export const FETCH_PLANETS_ERROR = "FETCH_PLANETS_ERROR";
export const CLEAR_LOGIN = "CLEAR_LOGIN";